### PR TITLE
SendMail: Always read email address from disk

### LINKED ISSUE #86: send address not overwritten
Hi,

## Describe the bug
we discovered a problem which shows up when we send manually a report then it is sent by this configured address, but if we schedule a report to automatically send each day, it is sent by the wrong address and not the one configured.

## Expected behavior
it should use the correct one

## Workarround
you can easily solve this problem by changing the address in PHP.

( https://github.com/Icinga/icingaweb2-module-reporting/blob/908d740ad4559a9171b9be3e489ceedd99fdae36/library/Reporting/Actions/SendMail.php )

Ref/NC/701482

Regards
Nathaniel

### PR DESCRIPTION
**Pull request by jhoxhaa**
fix #86

### CODE REVIEW

File: library/Reporting/Actions/SendMail.php [hunk 1]
```diff
@@ -28,7 +28,8 @@ public function execute(Report $report, array $config)
 
         $mail = new Mail();
 
-        $mail->setFrom(Config::module('reporting')->get('mail', 'from', 'reporting@icinga'));
```
Comment (lippserd) [inline library/Reporting/Actions/SendMail.php:31]: Please format the code in this way:

```
$mail->setFrom(
    Config::module('reporting', 'config', true)->get('mail', 'from', 'reporting@icinga'));
);
```

Otherwise, at first glance it looks like the `get()` call belongs to `$mail`.

**Review by lippserd — CHANGES_REQUESTED** [review]
Please also justify the change in the commit description, i.e. why it is necessary to read the configuration from disk.
