### PR TITLE
Fix Template discarding Images after editing

### LINKED ISSUE #159: Updating a report resets the background and logo image
## Describe the bug

Updating an existing template removes the values of the logo and background images.

## To Reproduce

1. Open an existing template which has a background and logo configured
2. Change any value, eg. Color
3. Save
4. Images get removed

## Your Environment

* Module version: 0.10.0
* Icinga Web 2 version and modules (System - About): 2.11.2
* Web browser and version: Google Chrome Version 107.0.5304.87 (Official Build) (x86_64)
* PHP version used (`php --version`): PHP 7.4.3
* Server operating system and version: Ubuntu 20.04.5 LTS

### PR DESCRIPTION
**Pull request by TAINCER**
fixes #159

### CODE REVIEW

**Review by yhabteab — COMMENTED** [review]
I find that this makes the code more complicated to get around the problem of multiple buttons in a form. Why not override the `hasBeenSubmitted()` method and decide by yourself if the form has been submitted or not? E.G.

```php
public function hasBeenSubmitted()
{
        return $this->hasBeenSent() && ($this->getPopulatedValue('submit') || $this->getPopulatedValue('remove'));
}
```

This way you don't have to work around the multiple button glitches and can handle all requests regularly in the `onSuccess()` handler.

**Comment by nilmerg** [comment]
I think https://github.com/Icinga/ipl-html/pull/107 might be a good use-case here. Please try this instead.
It can be populated like any other element and then behaves just as if the user chose a file only moments ago.

To populate a file element, use this as `value`:

```
[
    'file_name' => 'test.pdf',
    'content' => 'lorem ipsum dolorem',
    'content_type' => 'application/pdf'
]
```

`file_name` and `content_type` are optional. I wasn't quite sure which format suits best for populating the element. A class of sorts isn't an option IMHO as the population should be possible by standard types only. Here, for example, the file name and content type isn't even stored and an array with only a `content` key sounds unnecessarily complex. So a string only might also fit, what do you think?

**Comment by nilmerg** [comment]
Ah, ignore my previous post. :roll_eyes: @lippserd convinced me that we need a different solution for that.

File: application/controllers/TemplateController.php [hunk 1]
```diff
@@ -6,10 +6,13 @@
 
 use DateTime;
 use GuzzleHttp\Psr7\ServerRequest;
+use Icinga\Exception\MissingParameterException;
```
Comment (yhabteab) [inline application/controllers/TemplateController.php:9]: Some leftovers from your previous commit?

**Review by yhabteab — CHANGES_REQUESTED** [review]

File: application/controllers/TemplateController.php (hunk 1 above)
Comment (TAINCER) [reply application/controllers/TemplateController.php]: Yes, most of this is obsolete since the TemplateForm, etc. refactor PR.

File: library/Reporting/Web/Forms/TemplateForm.php [hunk 2]
```diff
@@ -186,7 +187,10 @@ public function onSuccess()
                     'mtime'    => $now
                 ]);
             } else {
-                if (isset($settings['remove_cover_page_background_image'])) {
+                if (
+                    isset($settings['remove_cover_page_background_image'])
+                    && $settings['remove_cover_page_background_image'] === 'y'
+                ) {
```
Comment (yhabteab) [inline library/Reporting/Web/Forms/TemplateForm.php:193]:
```suggestion
                if ($this->getValue('remove_cover_page_background_image', 'n') === 'y') {
```

File: library/Reporting/Web/Forms/TemplateForm.php [hunk 3]
```diff
@@ -196,7 +200,10 @@ public function onSuccess()
                     $settings['cover_page_background_image'] = $this->template->settings['cover_page_background_image'];
                 }
 
-                if (isset($settings['remove_cover_page_logo'])) {
+                if (
+                    isset($settings['remove_cover_page_logo'])
+                    && $settings['remove_cover_page_logo'] === 'y'
+                ) {
```
Comment (yhabteab) [inline library/Reporting/Web/Forms/TemplateForm.php:206]:
```suggestion
                if ($this->getValue('remove_cover_page_logo', 'n') === 'y') {
```

**Review by yhabteab — APPROVED** [review]
LFTM!

**Review by lippserd — APPROVED** [review]
