### PR TITLE
Fix `Scheduler` for monthly reports

### LINKED ISSUE #135: Monthly reports are not scheduled as expected
## Describe the bug

Currently, the monthly reports are not scheduled exactly after one month. Check the image below for reference.

monthlyreports

## To Reproduce

Create and schedule a monthly report.

## Expected behavior

Monthly reports must be scheduled exactly after 1 month, since the starting date. 

## Your Environment

* Module version: 
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About):
* Web browser and version:
* Icinga 2 version used (`icinga2 --version`):
* PHP version used (`php --version`):
* Server operating system and version:

### PR DESCRIPTION
**Pull request by raviks789**
The use of `$interval` has been removed and `$next->modify($modify)` is used in `$loop` callback.

[ref/IP/41334](https://rt.icinga.com/Ticket/Display.html?id=41334)

fixes #135

### CODE REVIEW

File: library/Reporting/Scheduler.php [hunk 1]
```diff
@@ -149,27 +149,23 @@ protected function add(Schedule $schedule)
         }
 
         $next = clone $start;
```
Comment (nilmerg) [inline library/Reporting/Scheduler.php:151]: This is fully obsolete once you're using the current time inside the timer again. Remove this and don't pass it on.

File: library/Reporting/Scheduler.php [hunk 2]
```diff
@@ -149,27 +149,23 @@ protected function add(Schedule $schedule)
...
 
         printf("Scheduling job %s to run at %s.\n", $name, $start->format('Y-m-d H:i:s'));
 
-        $loop = function () use (&$loop, $name, $callback, $interval, $schedule) {
+        $loop = function () use (&$loop, $name, $callback, $next, $modify, $schedule) {
             $callback();
 
-            $nextRun = (new \DateTime())
-                ->add(new \DateInterval("PT{$interval}S"));
+            $startTimestamp = $next->getTimestamp();
```
Comment (nilmerg) [inline library/Reporting/Scheduler.php:158]: This should be the current time, otherwise the timer is, once delayed, always delayed.

- $now
- 1 month after
- 2 months and 5 minutes after (+5 minutes delay)
- 3 months and 5 minutes after
- 4 months and 10 minutes after (+5 minutes delay)
- 5 months and 10 minutes after

With months this isn't that prevalent, but the shorter the interval the more it is.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: library/Reporting/Scheduler.php (hunk 1 above)
Comment (nilmerg) [reply library/Reporting/Scheduler.php:151]: No it's not, I've had not enough coffee yet -.-

**Review by nilmerg — APPROVED** [review]

**Comment by nilmerg** [comment]
Did also a little time travel adventure. Seems to work fine :joy:

> Scheduling job Schedule 1 to run at 2022-01-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-02-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-03-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-04-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-05-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-06-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-07-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-08-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-09-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-10-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-11-01 14:06:00.
> Scheduling job Schedule 1 to run at 2022-12-01 14:06:00.
> Scheduling job Schedule 1 to run at 2023-01-01 14:06:00.
> Scheduling job Schedule 1 to run at 2023-02-01 14:06:00.
> Scheduling job Schedule 1 to run at 2023-03-01 14:06:00.

**Comment by sklaes** [comment]
@raviks789
Is there any description of the bug that is fixed with this pull request?

Since last month we have the issue that no reports will be send automatically. A colleague of mine quickly developed a “Send Now”-Button in order to mitigate the problem:
https://github.com/Icinga/icingaweb2-module-reporting/issues/133

**Comment by raviks789** [comment]
@sklaes 
You can find the bug description here: #135.
